#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-glmnet
Version  : 1.0.0
Release  : 3
URL      : http://pypi.debian.net/glmnet/glmnet-1.0.0.tar.gz
Source0  : http://pypi.debian.net/glmnet/glmnet-1.0.0.tar.gz
Summary  : Python wrapper for glmnet
Group    : Development/Tools
License  : GPL-2.0
Requires: python-glmnet-python
BuildRequires : numpy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-Fix-README-bug.patch

%description
Python GLMNET
=============
>glmnet: Lasso and Elastic-Net Regularized Generalized Linear Models.

%package python
Summary: python components for the python-glmnet package.
Group: Default

%description python
python components for the python-glmnet package.


%prep
%setup -q -n glmnet-1.0.0
%patch1 -p1

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
